// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://velarix.dev/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://velarix.dev/support",
            "email": "support@velarix.dev"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return a JWT for console access. No authentication required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account with Argon2id password hashing. No authentication required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "user created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/reset-confirm": {
            "post": {
                "description": "Update password using a reset token provided via console logs. No authentication required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Confirm password reset",
                "parameters": [
                    {
                        "description": "Reset details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ResetConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/reset-request": {
            "post": {
                "description": "Generate a reset token and log it to the server console. No authentication required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Request password reset",
                "parameters": [
                    {
                        "description": "User email",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Basic status, version, and uptime for monitoring.",
                "tags": [
                    "System"
                ],
                "summary": "System health check",
                "responses": {
                    "200": {
                        "description": "health status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/keys": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve all API keys associated with the user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "List API keys",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"user@example.com\"",
                        "description": "User Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.APIKey"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "user not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/keys/generate": {
            "post": {
                "description": "Create a new labeled API key for the user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Generate a new API key",
                "parameters": [
                    {
                        "description": "Key details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GenerateKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.APIKey"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "user not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/keys/{key}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Mark an API key as revoked. Revoked keys return 401.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Revoke an API key",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"vx_12345\"",
                        "description": "API Key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"user@example.com\"",
                        "description": "User Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "key not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/org/usage": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve atomic metrics for the requesting organization.",
                "tags": [
                    "System"
                ],
                "summary": "Get organization usage",
                "responses": {
                    "200": {
                        "description": "usage metrics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    }
                }
            }
        },
        "/s/{session_id}/events": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Server-Sent Events (SSE) stream for real-time belief updates.",
                "tags": [
                    "Facts"
                ],
                "summary": "Stream session events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "event stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/export": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Generate a SOC2-ready CSV or PDF export of the session history with SHA-256 integrity hash.",
                "tags": [
                    "History"
                ],
                "summary": "Export audit log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Format: csv or pdf",
                        "name": "format",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "exported file",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/facts": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve all facts, optionally filtering for only logically 'Valid' ones.",
                "tags": [
                    "Facts"
                ],
                "summary": "List all facts in a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Only return valid facts",
                        "name": "valid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "list of facts",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.Fact"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Add a new fact to the reasoning graph. If root, it is manual. If derived, it requires justification sets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Facts"
                ],
                "summary": "Assert a new fact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fact definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.Fact"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "fact created",
                        "schema": {
                            "$ref": "#/definitions/core.Fact"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/facts/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve a fact by its ID within a session.",
                "tags": [
                    "Facts"
                ],
                "summary": "Get a single fact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "fact details",
                        "schema": {
                            "$ref": "#/definitions/core.Fact"
                        }
                    },
                    "404": {
                        "description": "fact not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/facts/{id}/impact": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Calculate the downstream effect of retracting a specific fact.",
                "tags": [
                    "Analysis"
                ],
                "summary": "Analyze impact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "impact report",
                        "schema": {
                            "$ref": "#/definitions/core.ImpactReport"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/facts/{id}/invalidate": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Manually invalidate a root premise, triggering a causal collapse of all dependents.",
                "tags": [
                    "Facts"
                ],
                "summary": "Invalidate a root fact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status invalidated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/facts/{id}/why": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve the justification tree for a specific fact.",
                "tags": [
                    "Analysis"
                ],
                "summary": "Explain a fact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "explanation tree",
                        "schema": {
                            "$ref": "#/definitions/core.ExplanationNode"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/history": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve the full chronological journal for a session.",
                "tags": [
                    "History"
                ],
                "summary": "Get session history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "audit trail",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.JournalEntry"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Manually append a custom event to the session's audit trail.",
                "tags": [
                    "History"
                ],
                "summary": "Append to journal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event to append",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.JournalEntry"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "event appended",
                        "schema": {
                            "$ref": "#/definitions/store.JournalEntry"
                        }
                    }
                }
            }
        },
        "/s/{session_id}/revalidate": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Clear the engine and replay the full journal through all validation rules. Returns an impact summary.",
                "tags": [
                    "Analysis"
                ],
                "summary": "Revalidate entire session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "revalidation summary",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/s/{session_id}/slice": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve the logically valid subset of facts formatted for LLM consumption.",
                "tags": [
                    "Facts"
                ],
                "summary": "Get context slice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Format: json or markdown",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max facts to return",
                        "name": "max_facts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "facts slice",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve summary info for all sessions currently held in RAM.",
                "tags": [
                    "Sessions"
                ],
                "summary": "List active sessions",
                "responses": {
                    "200": {
                        "description": "list of sessions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.sessionInfo"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.GenerateKeyRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "label": {
                    "type": "string",
                    "example": "Production"
                }
            }
        },
        "api.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "securepassword123"
                }
            }
        },
        "api.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "securepassword123"
                }
            }
        },
        "api.ResetConfirmRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "new_password": {
                    "type": "string",
                    "example": "newsecurepassword456"
                },
                "token": {
                    "type": "string",
                    "example": "a1b2c3"
                }
            }
        },
        "api.ResetRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "api.sessionInfo": {
            "type": "object",
            "properties": {
                "enforcement_mode": {
                    "type": "string"
                },
                "fact_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "core.ExplanationNode": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core.ExplanationNode"
                    }
                },
                "factID": {
                    "type": "string"
                }
            }
        },
        "core.Fact": {
            "type": "object",
            "properties": {
                "derivedStatus": {
                    "description": "Computed only by the engine",
                    "type": "number",
                    "format": "float64"
                },
                "id": {
                    "type": "string"
                },
                "idom": {
                    "description": "Dominator Tree",
                    "type": "string"
                },
                "isRoot": {
                    "description": "Root control",
                    "type": "boolean"
                },
                "justification_sets": {
                    "description": "OR-of-AND justification (for API/Journal backwards compatibility)",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "manualStatus": {
                    "type": "number",
                    "format": "float64"
                },
                "metadata": {
                    "description": "Internal system metadata (ignored by schema validation)",
                    "type": "object",
                    "additionalProperties": true
                },
                "payload": {
                    "description": "Arbitrary belief payload (validated against user schema)",
                    "type": "object",
                    "additionalProperties": true
                },
                "postOrder": {
                    "type": "integer"
                },
                "preOrder": {
                    "type": "integer"
                },
                "validJustificationCount": {
                    "description": "How many JustificationSets are fully valid",
                    "type": "integer"
                },
                "validation_errors": {
                    "description": "Schema Validation",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "core.ImpactReport": {
            "type": "object",
            "properties": {
                "action_count": {
                    "type": "integer"
                },
                "direct_count": {
                    "type": "integer"
                },
                "epistemic_loss": {
                    "type": "number"
                },
                "impacted_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "store.APIKey": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "is_revoked": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "integer"
                }
            }
        },
        "store.EventType": {
            "type": "string",
            "enum": [
                "assert",
                "invalidate",
                "cycle_violation",
                "snapshot_corruption",
                "confidence_adjusted",
                "revalidation_complete"
            ],
            "x-enum-varnames": [
                "EventAssert",
                "EventInvalidate",
                "EventCycleViolation",
                "EventSnapshotCorruption",
                "EventConfidenceAdjusted",
                "EventRevalidationComplete"
            ]
        },
        "store.JournalEntry": {
            "type": "object",
            "properties": {
                "fact": {
                    "$ref": "#/definitions/core.Fact"
                },
                "fact_id": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/store.EventType"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Velarix API",
	Description:      "The Epistemic State Layer for AI Agents.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
