package api

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
)

var (
	ActiveSessions = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "velarix_active_sessions_total",
		Help: "Current number of sessions loaded in RAM. Recommended alert: > 5000 per instance.",
	})

	ExtractionLatency = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "velarix_extraction_latency_ms",
		Help:    "End-to-end latency of the fact extraction call in milliseconds (success and failure). Recommended alert: P99 > 8000ms.",
		Buckets: []float64{10, 50, 100, 500, 1000, 3000, 8000, 15000},
	})

	ExtractionStage1DiscardedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_extraction_stage1_discarded_total",
		Help: "Total sentences discarded during Stage 1 sentence selection.",
	})

	ExtractionStage2UnresolvedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_extraction_stage2_unresolved_total",
		Help: "Total unresolved references detected during Stage 2 decontextualisation.",
	})

	ExtractionStage3EdgesProposedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_extraction_stage3_edges_proposed_total",
		Help: "Total dependency edges proposed by the LLM in Stage 3B (above threshold).",
	})

	ExtractionStage3EdgesAcceptedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_extraction_stage3_edges_accepted_total",
		Help: "Total dependency edges accepted by the TMS validator in Stage 3B.",
	})

	ExtractionStage3EdgesRejectedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_extraction_stage3_edges_rejected_total",
		Help: "Total dependency edges rejected by the TMS validator in Stage 3B.",
	})

	ExtractionStage4MissedClaimsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_extraction_stage4_missed_claims_total",
		Help: "Total missed claims recovered during Stage 4 coverage verification.",
	})

	ExtractionStage5ContradictionsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_extraction_stage5_contradictions_total",
		Help: "Total pre-assertion contradictions detected during Stage 5 consistency pre-check.",
	})

	// SRL Pipeline Metrics (Tier 1 / Tier 2)
	SRLExtractionLatency = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "velarix_srl_extraction_latency_ms",
		Help:    "End-to-end latency of SRL extraction pipeline in milliseconds.",
		Buckets: []float64{5, 10, 25, 50, 100, 250, 500, 1000},
	})

	SRLFactsExtractedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_srl_facts_extracted_total",
		Help: "Total facts extracted by the SRL pipeline (Tier 1/2).",
	})

	SRLEdgesProposedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_srl_edges_proposed_total",
		Help: "Total dependency edges proposed by the SRL discourse analysis.",
	})

	SRLEdgesAcceptedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_srl_edges_accepted_total",
		Help: "Total dependency edges accepted after TMS validation in SRL pipeline.",
	})

	SRLEdgesRejectedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_srl_edges_rejected_total",
		Help: "Total dependency edges rejected by TMS validation in SRL pipeline.",
	})

	SRLFallbackTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_srl_fallback_total",
		Help: "Total sentences that required LLM fallback in hybrid mode (Tier 2).",
	})

	SRLAmbiguousTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_srl_ambiguous_total",
		Help: "Total ambiguous parse pairs generated by the SRL pipeline.",
	})

	VerifierFailures = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "velarix_verifier_failures_total",
		Help: "Total OpenAI consistency-verifier call failures by reason. Reasons: timeout, api_error, parse_error.",
	}, []string{"reason"})

	AutoRetractionsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_auto_retractions_total",
		Help: "Total facts automatically retracted due to detected contradictions.",
	})

	FactsExpiredTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "velarix_facts_expired_total",
		Help: "Total facts expired via ValidUntil sweeps (fact_expired).",
	})

	BadgerDiskUsage = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "velarix_badger_disk_usage_bytes",
		Help: "Total bytes used by BadgerDB. Recommended alert: > 80% of volume capacity.",
	})

	FactAssertionLatency = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "velarix_fact_assertion_latency_ms",
		Help:    "Latency of fact assertions in milliseconds. Recommended alert: P99 > 500ms.",
		Buckets: []float64{10, 50, 100, 250, 500, 1000},
	})

	APIRequests = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "velarix_api_requests_total",
		Help: "Total API requests by endpoint and status. Recommended alert: status=5xx rate > 1%.",
	}, []string{"endpoint", "status"})

	CacheRatio = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "velarix_cache_ratio",
		Help: "GetSlice cache hit/miss count. Recommended alert: miss rate > 50% on warm sessions.",
	}, []string{"type"})

	PruneLatency = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "velarix_prune_latency_ms",
		Help:    "Latency of causal collapse/pruning in milliseconds. Recommended alert: P99 > 100ms.",
		Buckets: []float64{1, 5, 10, 50, 100, 500},
	})

	SLOSuccessRate = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "velarix_slo_success_rate",
		Help: "Service Level Objective for overall request success (99.9% target)",
	}, []string{"result"})
)

func InitTracer() (*sdktrace.TracerProvider, error) {
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String("velarix"),
		)),
	)
	otel.SetTracerProvider(tp)
	return tp, nil
}
